name: Vercel Production Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  NEXT_PUBLIC_CHAVE_PIX: ${{ secrets.NEXT_PUBLIC_CHAVE_PIX}}
  NEXT_PUBLIC_NOME_PIX: ${{ secrets.NEXT_PUBLIC_NOME_PIX }}
  NEXT_PUBLIC_ID_PIX: ${{ secrets.NEXT_PUBLIC_ID_PIX}}
  NEXT_PUBLIC_TYPE_PIX: ${{ secrets.NEXT_PUBLIC_TYPE_PIX}}
  NEXT_PUBLIC_CITY_PIX: ${{ secrets.NEXT_PUBLIC_CITY_PIX }}
on:
  push:
    branches:
    
      - master
jobs:

  Deploy-Production:
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
       
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Run Prisma Migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npx prisma migrate deploy

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Run the tests
        run: npm run test
        
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}